-- 1. Criação dos Bancos
CREATE DATABASE WSO2_SHARED_DB;
CREATE DATABASE WSO2AM_DB;
GO

ALTER DATABASE WSO2_SHARED_DB SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE WSO2_SHARED_DB SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
ALTER DATABASE WSO2AM_DB SET ALLOW_SNAPSHOT_ISOLATION ON;
ALTER DATABASE WSO2AM_DB SET READ_COMMITTED_SNAPSHOT ON WITH ROLLBACK IMMEDIATE;
GO

USE master;
CREATE LOGIN wso2carbon WITH PASSWORD = 'Wso2carbon@2026', CHECK_POLICY = OFF;
GO

USE WSO2_SHARED_DB;
CREATE USER wso2carbon FOR LOGIN wso2carbon;
EXEC sp_addrolemember 'db_owner', 'wso2carbon';
GO

USE WSO2AM_DB;
CREATE USER wso2carbon FOR LOGIN wso2carbon ;
EXEC sp_addrolemember 'db_owner', 'wso2carbon';
GO